language: perl
perl:
  - "5.24"
  #- "5.20"
  - "5.18"
  #- "5.16"
  #- "5.14"

sudo: false
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

addons:
  apt:
    packages:
      - samtools
      - ncbi-blast+
      - ncbi-blast+-legacy
      - clustalw
      - bwa
      - hmmer
      - emboss
      - probcons
      - wise
      #- muscle
      #- bedtools
      #- mafft

install:
    #These are recommended or required Perl libraries
    - "cpanm Bio::Perl 2>&1 | tail -n 1"
    - "cpanm Bio::FeatureIO 2>&1 | tail -n 1"
    - "cpanm IPC::Run XML::Twig 2>&1 | tail -n 1"
    - "cpanm Config::Any 2>&1 | tail -n 1"
    #- "SAMTOOLS=( dirname `which samtools` ) cpanm Bio::DB::Sam 2>&1 | tail -n 1"

script:
    - "perl ./Build.PL --accept"
    - "./Build test"

#after_success:
#    - ./travis_scripts/trigger-dockerhub.sh

#TODO - send emails to bioperl-guts-l
notifications:
  email:
    recipients:
      #- bioperl-guts-l@lists.open-bio.org
      - cjfields1@gmail.com
    on_success: change
    on_failure: change

# whitelist branches
branches:
  only:
    - master
